version: "3.8"
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
  app:
    build: ./application/
    ports:
      - '8000:8000'
    restart: on-failure
    depends_on:
      - db
    links: 
      - db
    environment:
      PGDATABASE: postgres
      PGUSER: postgres
      PGPASSWORD: postgres
